# Generated by Django 4.2 on 2023-04-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField()),
                ('text', models.TextField()),
                ('data_pub', models.DateTimeField(auto_now_add=True)),
                ('category', models.SlugField(choices=[('uncos', 'Новости')], default='uncos', max_length=10)),
            ],
        ),
    ]
